/**
 * Generated by Scrooge
 *   version: 18.6.0
 *   rev: 4d5c08c211c7320d0d225bba35a74bdc47c750e6
 *   built at: 20180617-181945
 */
package thrift

import com.twitter.io.Buf
import com.twitter.scrooge.{
  LazyTProtocol,
  TFieldBlob,
  ThriftException,
  ThriftStruct,
  ThriftStructCodec3,
  ThriftStructFieldInfo,
  ThriftStructMetaData,
  ThriftUtil,
  ValidatingThriftStruct,
  ValidatingThriftStructCodec3
}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport, TIOStreamTransport}
import java.io.ByteArrayInputStream
import java.nio.ByteBuffer
import java.util.Arrays
import java.util.concurrent.atomic.AtomicInteger
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object Location extends ValidatingThriftStructCodec3[Location] {
  val NoPassthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("Location")
  val LatitudeField = new TField("latitude", TType.DOUBLE, 1)
  val LatitudeFieldManifest = implicitly[Manifest[Double]]
  val LongitudeField = new TField("longitude", TType.DOUBLE, 2)
  val LongitudeFieldManifest = implicitly[Manifest[Double]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      LatitudeField,
      false,
      true,
      LatitudeFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    ),
    new ThriftStructFieldInfo(
      LongitudeField,
      false,
      true,
      LongitudeFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: Location): Unit = {
  }

  /**
   * Checks that the struct is a valid as a new instance. If there are any missing required or
   * construction required fields, return a non-empty list.
   */
  def validateNewInstance(item: Location): scala.Seq[com.twitter.scrooge.validation.Issue] = {
    val buf = scala.collection.mutable.ListBuffer.empty[com.twitter.scrooge.validation.Issue]

    buf ++= validateField(item.latitude)
    buf ++= validateField(item.longitude)
    buf.toList
  }

  def withoutPassthroughFields(original: Location): Location =
    new Immutable(
      latitude =
        {
          val field = original.latitude
          field
        },
      longitude =
        {
          val field = original.longitude
          field
        }
    )

  override def encode(_item: Location, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }


  private[this] def lazyDecode(_iprot: LazyTProtocol): Location = {

    var latitude: Double = 0.0
    var _got_latitude = false
    var longitude: Double = 0.0
    var _got_longitude = false

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.DOUBLE =>
    
                latitude = readLatitudeValue(_iprot)
                _got_latitude = true
              case _actualType =>
                val _expectedType = TType.DOUBLE
                throw new TProtocolException(
                  "Received wrong type for field 'latitude' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.DOUBLE =>
    
                longitude = readLongitudeValue(_iprot)
                _got_longitude = true
              case _actualType =>
                val _expectedType = TType.DOUBLE
                throw new TProtocolException(
                  "Received wrong type for field 'longitude' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_latitude) throw new TProtocolException("Required field 'latitude' was not found in serialized data for struct Location")
    if (!_got_longitude) throw new TProtocolException("Required field 'longitude' was not found in serialized data for struct Location")
    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      latitude,
      longitude,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  override def decode(_iprot: TProtocol): Location =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[thrift] def eagerDecode(_iprot: TProtocol): Location = {
    var latitude: Double = 0.0
    var _got_latitude = false
    var longitude: Double = 0.0
    var _got_longitude = false
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.DOUBLE =>
                latitude = readLatitudeValue(_iprot)
                _got_latitude = true
              case _actualType =>
                val _expectedType = TType.DOUBLE
                throw new TProtocolException(
                  "Received wrong type for field 'latitude' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.DOUBLE =>
                longitude = readLongitudeValue(_iprot)
                _got_longitude = true
              case _actualType =>
                val _expectedType = TType.DOUBLE
                throw new TProtocolException(
                  "Received wrong type for field 'longitude' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_latitude) throw new TProtocolException("Required field 'latitude' was not found in serialized data for struct Location")
    if (!_got_longitude) throw new TProtocolException("Required field 'longitude' was not found in serialized data for struct Location")
    new Immutable(
      latitude,
      longitude,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    latitude: Double,
    longitude: Double
  ): Location =
    new Immutable(
      latitude,
      longitude
    )

  def unapply(_item: Location): _root_.scala.Option[_root_.scala.Tuple2[Double, Double]] = _root_.scala.Some(_item.toTuple)


  @inline private[thrift] def readLatitudeValue(_iprot: TProtocol): Double = {
    _iprot.readDouble()
  }

  @inline private def writeLatitudeField(latitude_item: Double, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(LatitudeField)
    writeLatitudeValue(latitude_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeLatitudeValue(latitude_item: Double, _oprot: TProtocol): Unit = {
    _oprot.writeDouble(latitude_item)
  }

  @inline private[thrift] def readLongitudeValue(_iprot: TProtocol): Double = {
    _iprot.readDouble()
  }

  @inline private def writeLongitudeField(longitude_item: Double, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(LongitudeField)
    writeLongitudeValue(longitude_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeLongitudeValue(longitude_item: Double, _oprot: TProtocol): Unit = {
    _oprot.writeDouble(longitude_item)
  }


  object Immutable extends ThriftStructCodec3[Location] {
    override def encode(_item: Location, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): Location = Location.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[Location] = Location.metaData
  }

  /**
   * The default read-only implementation of Location.  You typically should not need to
   * directly reference this class; instead, use the Location.apply method to construct
   * new instances.
   */
  class Immutable(
      val latitude: Double,
      val longitude: Double,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends Location {
    def this(
      latitude: Double,
      longitude: Double
    ) = this(
      latitude,
      longitude,
      Map.empty[Short, TFieldBlob]
    )
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
      _proto: LazyTProtocol,
      _buf: Array[Byte],
      _start_offset: Int,
      _end_offset: Int,
      val latitude: Double,
      val longitude: Double,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends Location {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }


    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide significant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the Location trait with additional state or
   * behavior and implement the read-only methods from Location using an underlying
   * instance.
   */
  trait Proxy extends Location {
    protected def _underlying_Location: Location
    override def latitude: Double = _underlying_Location.latitude
    override def longitude: Double = _underlying_Location.longitude
    override def _passthroughFields = _underlying_Location._passthroughFields
  }
}

/**
 * Prefer the companion object's [[thrift.Location.apply]]
 * for construction if you don't need to specify passthrough fields.
 */
trait Location
  extends ThriftStruct
  with _root_.scala.Product2[Double, Double]
  with ValidatingThriftStruct[Location]
  with java.io.Serializable
{
  import Location._

  def latitude: Double
  def longitude: Double

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = latitude
  def _2 = longitude

  def toTuple: _root_.scala.Tuple2[Double, Double] = {
    (
      latitude,
      longitude
    )
  }


  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (true) {
                writeLatitudeValue(latitude, _oprot)
                _root_.scala.Some(Location.LatitudeField)
              } else {
                _root_.scala.None
              }
            case 2 =>
              if (true) {
                writeLongitudeValue(longitude, _oprot)
                _root_.scala.Some(Location.LongitudeField)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            _root_.scala.Some(TFieldBlob(_field, Buf.ByteArray.Owned(_buff.getArray())))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): Location = {
    var latitude: Double = this.latitude
    var longitude: Double = this.longitude
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        latitude = readLatitudeValue(_blob.read)
      case 2 =>
        longitude = readLongitudeValue(_blob.read)
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      latitude,
      longitude,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): Location = {
    var latitude: Double = this.latitude
    var longitude: Double = this.longitude

    _fieldId match {
      case 1 =>
        latitude = 0.0
      case 2 =>
        longitude = 0.0
      case _ =>
    }
    new Immutable(
      latitude,
      longitude,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetLatitude: Location = unsetField(1)

  def unsetLongitude: Location = unsetField(2)


  override def write(_oprot: TProtocol): Unit = {
    Location.validate(this)
    _oprot.writeStructBegin(Struct)
    writeLatitudeField(latitude, _oprot)
    writeLongitudeField(longitude, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    latitude: Double = this.latitude,
    longitude: Double = this.longitude,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): Location =
    new Immutable(
      latitude,
      longitude,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[Location]

  private def _equals(x: Location, y: Location): Boolean =
      x.productArity == y.productArity &&
      x.productIterator.sameElements(y.productIterator)

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _equals(this, other.asInstanceOf[Location]) &&
      _passthroughFields == other.asInstanceOf[Location]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 2

  override def productElement(n: Int): Any = n match {
    case 0 => this.latitude
    case 1 => this.longitude
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "Location"

  def _codec: ValidatingThriftStructCodec3[Location] = Location
}

